import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const receiptStyles = `
  * { box-sizing: border-box; }
  body {
    margin: 0;
    padding: 16px;
    font-family: Arial, Helvetica, sans-serif;
    background: #f3f4f6;
    color: #111827;
  }
  .sheet {
    display: flex;
    gap: 14px;
    align-items: stretch;
  }
  .receipt {
    flex: 1;
    background: white;
    border: 2px solid #111827;
    border-radius: 14px;
    padding: 16px;
    min-height: 100%;
  }
  .head {
    border-bottom: 1px solid #d1d5db;
    padding-bottom: 10px;
    margin-bottom: 12px;
    text-align: center;
  }
  .head h1 {
    margin: 0;
    font-size: 20px;
    letter-spacing: 0.08em;
  }
  .head h3 {
    margin: 8px 0 0;
  }
  .copy {
    margin-top: 6px;
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
  }
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px 12px;
    font-size: 13px;
  }
  .field {
    border: 1px solid #e5e7eb;
    border-radius: 10px;
    padding: 8px 10px;
    background: #fafafa;
  }
  .label {
    display: block;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #6b7280;
    margin-bottom: 4px;
  }
  .value {
    font-size: 13px;
    font-weight: 700;
    color: #111827;
    word-break: break-word;
  }
  .summary {
    margin-top: 12px;
    border-top: 1px dashed #d1d5db;
    padding-top: 12px;
    display: grid;
    gap: 8px;
  }
  .summaryRow {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    font-size: 13px;
  }
  .summaryRow strong {
    min-width: 120px;
  }
  .footer {
    margin-top: 12px;
    padding-top: 10px;
    border-top: 1px solid #d1d5db;
    display: flex;
    justify-content: space-between;
    gap: 12px;
    font-size: 12px;
    color: #4b5563;
  }
  @page {
    size: A4 landscape;
    margin: 8mm;
  }
  @media print {
    body {
      background: white;
      padding: 0;
    }
    .sheet {
      gap: 10px;
    }
    .receipt {
      break-inside: avoid;
    }
  }
`;

const formatMoney = (value) =>
  `Rs. ${Number(value || 0).toLocaleString("en-IN")}`;

const formatReceiptDate = (value) => {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? "-"
    : date.toLocaleString("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
      });
};

const readValue = (value) =>
  value === undefined || value === null || value === "" ? "-" : value;

const normalizeReceiptData = (receipt = {}) => ({
  paymentId: readValue(receipt.paymentId || receipt.transactionId || receipt._id),
  paidAt: formatReceiptDate(receipt.paidAt),
  amount: formatMoney(receipt.amount),
  studentName: readValue(receipt.studentName || receipt.name),
  fatherName: readValue(receipt.fathername),
  course: readValue(receipt.course),
  semester: readValue(receipt.semester),
  enrollment: readValue(receipt.enrollment),
  paymentMethod: readValue(receipt.paymentMethod),
});

const ReceiptCopy = ({ receipt, copyName }) => (
  <div className="receipt">
    <div className="head">
      <h1>Shakuntala Krishna Institute of Technology</h1>
      <h3>FEE RECEIPT</h3>
      <div className="copy">{copyName}</div>
    </div>

    <div className="grid">
      <div className="field">
        <span className="label">Receipt / Transaction ID</span>
        <span className="value">{receipt.paymentId}</span>
      </div>
      <div className="field">
        <span className="label">Date</span>
        <span className="value">{receipt.paidAt}</span>
      </div>
      <div className="field">
        <span className="label">Student Name</span>
        <span className="value">{receipt.studentName}</span>
      </div>
      <div className="field">
        <span className="label">Father Name</span>
        <span className="value">{receipt.fatherName}</span>
      </div>
      <div className="field">
        <span className="label">Class / Course</span>
        <span className="value">{receipt.course}</span>
      </div>
      <div className="field">
        <span className="label">Semester</span>
        <span className="value">{receipt.semester}</span>
      </div>
      <div className="field">
        <span className="label">Enrollment</span>
        <span className="value">{receipt.enrollment}</span>
      </div>
      <div className="field">
        <span className="label">Payment Method</span>
        <span className="value">{receipt.paymentMethod}</span>
      </div>
    </div>

    <div className="summary">
      <div className="summaryRow">
        <strong>Amount Paid</strong>
        <span>{receipt.amount}</span>
      </div>
    </div>

    <div className="footer">
      <span>Generated by SKIT ERP</span>
      <span>Keep this receipt for record</span>
    </div>
  </div>
);

export const PaymentReceiptSheet = ({ receipt }) => {
  const normalizedReceipt = normalizeReceiptData(receipt);

  return (
    <div className="sheet">
      <ReceiptCopy receipt={normalizedReceipt} copyName="Office Copy" />
      <ReceiptCopy receipt={normalizedReceipt} copyName="Student Copy" />
    </div>
  );
};

const getReceiptDocumentHtml = (receipt) => `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Fee Receipt</title>
    <style>${receiptStyles}</style>
  </head>
  <body>${renderToStaticMarkup(<PaymentReceiptSheet receipt={receipt} />)}</body>
</html>`;

export const printPaymentReceipt = (receipt, receiptWindow) => {
  const printWindow =
    receiptWindow || window.open("", "_blank", "width=1400,height=900");

  if (!printWindow) {
    window.alert("Popup blocked. Please allow popups to print the receipt.");
    return;
  }

  printWindow.document.open();
  printWindow.document.write(getReceiptDocumentHtml(receipt));
  printWindow.document.close();
  printWindow.focus();

  window.setTimeout(() => {
    printWindow.print();
    printWindow.close();
  }, 500);
};

export default PaymentReceiptSheet;
